<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::Statement("
            INSERT INTO `countries` (`iso2`, `name_nl`, `name`, `iso3`, `isd`, `is_eu`) VALUES
            ('AD', 'Andorra', 'Andorra', 'AND', '376', 0),
            ('AE', 'Verenigde Arabische Emiraten', 'United Arab Emirates', 'ARE', '971', 0),
            ('AF', 'Afghanistan', 'Afghanistan', 'AFG', '93', 0),
            ('AG', 'Antigua en Barbuda', 'Antigua and Barbuda', 'ATG', '1-268', 0),
            ('AI', 'Anguilla', 'Anguilla', 'AIA', '1-264', 0),
            ('AL', 'Albanië', 'Albania', 'ALB', '355', 0),
            ('AM', 'Armenië', 'Armenia', 'ARM', '374', 0),
            ('AO', 'Angola', 'Angola', 'AGO', '244', 0),
            ('AQ', 'Antarctica', 'Antarctica', 'ATA', '672', 0),
            ('AR', 'Argentinië', 'Argentina', 'ARG', '54', 0),
            ('AS', 'Amerikaans-Samoa', 'American Samoa', 'ASM', '1-684', 0),
            ('AT', 'Oostenrijk', 'Austria', 'AUT', '43', 1),
            ('AU', 'Australië', 'Australia', 'AUS', '61', 0),
            ('AW', 'Aruba', 'Aruba', 'ABW', '297', 0),
            ('AX', 'Åland', 'Åland Islands', 'ALA', '358', 0),
            ('AZ', 'Azerbeidzjan', 'Azerbaijan', 'AZE', '994', 0),
            ('BA', 'Bosnië en Herzegovina', 'Bosnia and Herzegovina', 'BIH', '387', 0),
            ('BB', 'Barbados', 'Barbados', 'BRB', '1-246', 0),
            ('BD', 'Bangladesh', 'Bangladesh', 'BGD', '880', 0),
            ('BE', 'België', 'Belgium', 'BEL', '32', 1),
            ('BF', 'Burkina Faso', 'Burkina Faso', 'BFA', '226', 0),
            ('BG', 'Bulgarije', 'Bulgaria', 'BGR', '359', 1),
            ('BH', 'Bahrein', 'Bahrain', 'BHR', '973', 0),
            ('BI', 'Burundi', 'Burundi', 'BDI', '257', 0),
            ('BJ', 'Benin', 'Benin', 'BEN', '229', 0),
            ('BL', 'Saint-Barthélemy', 'Saint-Barthélemy', 'BLM', '652', 0),
            ('BM', 'Bermuda', 'Bermuda', 'BMU', '1-441', 0),
            ('BN', 'Brunei', 'Brunei Darussalam', 'BRN', '673', 0),
            ('BO', 'Bolivia', 'Bolivia', 'BOL', '591', 0),
            ('BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'BES', '599-7', 0),
            ('BR', 'Brazilië', 'Brazil', 'BRA', '55', 0),
            ('BS', 'Bahama\'s', 'Bahamas', 'BHS', '1-242', 0),
            ('BT', 'Bhutan', 'Bhutan', 'BTN', '975', 0),
            ('BV', 'Bouveteiland', 'Bouvet Island', 'BVT', '47', 0),
            ('BW', 'Botswana', 'Botswana', 'BWA', '267', 0),
            ('BY', 'Wit-Rusland', 'Belarus', 'BLR', '375', 0),
            ('BZ', 'Belize', 'Belize', 'BLZ', '501', 0),
            ('CA', 'Canada', 'Canada', 'CAN', '1', 0),
            ('CC', 'Cocoseilanden', 'Cocos (Keeling) Islands', 'CCK', '61', 0),
            ('CD', 'Congo (DRC)', 'Congo (DRC)', 'COD', '242', 0),
            ('CF', 'Centraal-Afrikaanse Republiek', 'Central African Republic', 'CAF', '236', 0),
            ('CG', 'Congo-Brazzaville', 'Congo-Brazzaville', 'COG', '178', 0),
            ('CH', 'Zwitserland', 'Switzerland', 'CHE', '41', 0),
            ('CI', 'Ivoorkust', 'Ivory Coast', 'CIV', '225', 0),
            ('CK', 'Cookeilanden', 'Cook Islands', 'COK', '682', 0),
            ('CL', 'Chili', 'Chile', 'CHL', '56', 0),
            ('CM', 'Kameroen', 'Cameroon', 'CMR', '237', 0),
            ('CN', 'China', 'China', 'CHN', '86', 0),
            ('CO', 'Colombia', 'Colombia', 'COL', '57', 0),
            ('CR', 'Costa Rica', 'Costa Rica', 'CRI', '506', 0),
            ('CU', 'Cuba', 'Cuba', 'CUB', '53', 0),
            ('CV', 'Kaapverdië', 'Cape Verde', 'CPV', '238', 0),
            ('CW', 'Curaçao', 'Curaçao', 'CUW', '599', 0),
            ('CX', 'Christmaseiland', 'Christmas Island', 'CXR', '61', 0),
            ('CY', 'Cyprus', 'Cyprus', 'CYP', '357', 1),
            ('CZ', 'Tsjechië', 'Czechia', 'CZE', '420', 1),
            ('DE', 'Duitsland', 'Germany', 'DEU', '49', 1),
            ('DJ', 'Djibouti', 'Djibouti', 'DJI', '253', 0),
            ('DK', 'Denemarken', 'Denmark', 'DNK', '45', 1),
            ('DM', 'Dominica', 'Dominica', 'DMA', '1-767', 0),
            ('DO', 'Dominicaanse Republiek', 'Dominican Republic', 'DOM', '1-809', 0),
            ('DZ', 'Algerije', 'Algeria', 'DZA', '213', 0),
            ('EC', 'Ecuador', 'Ecuador', 'ECU', '593', 0),
            ('EE', 'Estland', 'Estonia', 'EST', '372', 1),
            ('EG', 'Egypte', 'Egypt', 'EGY', '20', 0),
            ('EH', 'Westelijke Sahara', 'Western Sahara', 'ESH', '212', 0),
            ('ER', 'Eritrea', 'Eritrea', 'ERI', '291', 0),
            ('ES', 'Spanje', 'Spain', 'ESP', '34', 1),
            ('ET', 'Ethiopië', 'Ethiopia', 'ETH', '251', 0),
            ('FI', 'Finland', 'Finland', 'FIN', '358', 1),
            ('FJ', 'Fiji', 'Fiji', 'FJI', '679', 0),
            ('FK', 'Falklandeilanden', 'Falkland Islands (Malvinas)', 'FLK', '500', 0),
            ('FM', 'Micronesia', 'Micronesia, Federated States of', 'FSM', '691', 0),
            ('FO', 'Faeröer', 'Faroe Islands', 'FRO', '298', 0),
            ('FR', 'Frankrijk', 'France', 'FRA', '33', 1),
            ('GA', 'Gabon', 'Gabon', 'GAB', '241', 0),
            ('GB', 'Verenigd Koninkrijk', 'United Kingdom', 'GBR', '44', 1),
            ('GD', 'Grenada', 'Grenada', 'GRD', '1-473', 0),
            ('GE', 'Georgië', 'Georgia', 'GEO', '995', 0),
            ('GF', 'Frans-Guyana', 'French Guiana', 'GUF', '594', 0),
            ('GG', 'Guernsey', 'Guernsey', 'GGY', '44-1481', 0),
            ('GH', 'Ghana', 'Ghana', 'GHA', '233', 0),
            ('GI', 'Gibraltar', 'Gibraltar', 'GIB', '350', 0),
            ('GL', 'Groenland', 'Greenland', 'GRL', '299', 0),
            ('GM', 'Gambia', 'Gambia', 'GMB', '220', 0),
            ('GN', 'Guinee', 'Guinea', 'GIN', '224', 0),
            ('GP', 'Guadeloupe', 'Guadeloupe', 'GLP', '590', 0),
            ('GQ', 'Equatoriaal-Guinea', 'Equatorial Guinea', 'GNQ', '240', 0),
            ('GR', 'Griekenland', 'Greece', 'GRC', '30', 1),
            ('GS', 'Zuid-Georgia en de Zuidelijke Sandwicheilanden', 'South Georgia and the South Sandwich Islands', 'SGS', '500', 0),
            ('GT', 'Guatemala', 'Guatemala', 'GTM', '502', 0),
            ('GU', 'Guam', 'Guam', 'GUM', '1-671', 0),
            ('GW', 'Guinee-Bissau', 'Guinea-bissau', 'GNB', '245', 0),
            ('GY', 'Guyana', 'Guyana', 'GUY', '592', 0),
            ('HK', 'Hongkong', 'Hong Kong', 'HKG', '852', 0),
            ('HM', 'Heard en McDonaldeilanden', 'Heard Island and McDonald Islands', 'HMD', '011', 0),
            ('HN', 'Honduras', 'Honduras', 'HND', '504', 0),
            ('HR', 'Kroatië', 'Croatia', 'HRV', '385', 1),
            ('HT', 'Haïti', 'Haiti', 'HTI', '509', 0),
            ('HU', 'Hongarije', 'Hungary', 'HUN', '36', 1),
            ('ID', 'Indonesië', 'Indonesia', 'IDN', '62', 0),
            ('IE', 'Ierland', 'Ireland', 'IRL', '353', 1),
            ('IL', 'Israël', 'Israel', 'ISR', '972', 0),
            ('IM', 'Man', 'Isle of Man', 'IMN', '44-1624', 0),
            ('IN', 'India', 'India', 'IND', '91', 0),
            ('IO', 'Brits Indische Oceaanterritorium', 'British Indian Ocean Territory', 'IOT', '246', 0),
            ('IQ', 'Irak', 'Iraq', 'IRQ', '964', 0),
            ('IR', 'Iran', 'Iran (Islamic Republic of)', 'IRN', '98', 0),
            ('IS', 'IJsland', 'Iceland', 'ISL', '354', 0),
            ('IT', 'Italië', 'Italy', 'ITA', '39', 1),
            ('JE', 'Jersey', 'Jersey', 'JEY', '44-1534', 1),
            ('JM', 'Jamaica', 'Jamaica', 'JAM', '1-876', 0),
            ('JO', 'Jordanië', 'Jordan', 'JOR', '962', 0),
            ('JP', 'Japan', 'Japan', 'JPN', '81', 0),
            ('KE', 'Kenia', 'Kenya', 'KEN', '254', 0),
            ('KG', 'Kirgizië', 'Kyrgyzstan', 'KGZ', '996', 0),
            ('KH', 'Cambodja', 'Cambodia', 'KHM', '855', 0),
            ('KI', 'Kiribati', 'Kiribati', 'KIR', '686', 0),
            ('KM', 'Comoren', 'Comoros', 'COM', '269', 0),
            ('KN', 'Saint Kitts en Nevis', 'Saint Kitts and Nevis', 'KNA', '1-869', 0),
            ('KP', 'Noord-Korea', 'Democratic People\'s Republic of Korea (North Korea)', 'PRK', '850', 0),
            ('KR', 'Zuid-Korea', 'Republic of Korea (South Korea)', 'KOR', '82', 0),
            ('KW', 'Koeweit', 'Kuwait', 'KWT', '965', 0),
            ('KY', 'Kaaimaneilanden', 'Cayman Islands', 'CYM', '1-345', 0),
            ('KZ', 'Kazachstan', 'Kazakhstan', 'KAZ', '7', 0),
            ('LA', 'Laos', 'Lao People\'s Democratic Republic', 'LAO', '856', 0),
            ('LB', 'Libanon', 'Lebanon', 'LBN', '961', 0),
            ('LC', 'Saint Lucia', 'Saint Lucia', 'LCA', '1-758', 0),
            ('LI', 'Liechtenstein', 'Liechtenstein', 'LIE', '423', 0),
            ('LK', 'Sri Lanka', 'Sri Lanka', 'LKA', '94', 0),
            ('LR', 'Liberia', 'Liberia', 'LBR', '231', 0),
            ('LS', 'Lesotho', 'Lesotho', 'LSO', '266', 0),
            ('LT', 'Litouwen', 'Lithuania', 'LTU', '370', 1),
            ('LU', 'Luxemburg', 'Luxembourg', 'LUX', '352', 1),
            ('LV', 'Letland', 'Latvia', 'LVA', '371', 1),
            ('LY', 'Libië', 'Libya', 'LBY', '218', 0),
            ('MA', 'Marokko', 'Morocco', 'MAR', '212', 0),
            ('MC', 'Monaco', 'Monaco', 'MCO', '377', 0),
            ('MD', 'Moldavië', 'Moldova', 'MDA', '373', 0),
            ('ME', 'Montenegro', 'Montenegro', 'MNE', '382', 0),
            ('MF', 'Sint-Maarten', 'Saint-Martin (French part)', 'MAF', '663', 0),
            ('MG', 'Madagaskar', 'Madagascar', 'MDG', '261', 0),
            ('MH', 'Marshalleilanden', 'Marshall Islands', 'MHL', '692', 0),
            ('MK', 'Noord-Macedonië', 'North Macedonia', 'MKD', '389', 0),
            ('ML', 'Mali', 'Mali', 'MLI', '223', 0),
            ('MM', 'Myanmar', 'Myanmar', 'MMR', '95', 0),
            ('MN', 'Mongolië', 'Mongolia', 'MNG', '976', 0),
            ('MO', 'Macau', 'Macao', 'MAC', '853', 0),
            ('MP', 'Noordelijke Marianen', 'Northern Mariana Islands', 'MNP', '1-670', 0),
            ('MQ', 'Martinique', 'Martinique', 'MTQ', '596', 0),
            ('MR', 'Mauritanië', 'Mauritania', 'MRT', '222', 0),
            ('MS', 'Montserrat', 'Montserrat', 'MSR', '1-664', 0),
            ('MT', 'Malta', 'Malta', 'MLT', '356', 1),
            ('MU', 'Mauritius', 'Mauritius', 'MUS', '230', 0),
            ('MV', 'Maldiven', 'Maldives', 'MDV', '960', 0),
            ('MW', 'Malawi', 'Malawi', 'MWI', '265', 0),
            ('MX', 'Mexico', 'Mexico', 'MEX', '52', 0),
            ('MY', 'Maleisië', 'Malaysia', 'MYS', '60', 0),
            ('MZ', 'Mozambique', 'Mozambique', 'MOZ', '258', 0),
            ('NA', 'Namibië', 'Namibia', 'NAM', '264', 0),
            ('NC', 'Nieuw-Caledonië', 'New Caledonia', 'NCL', '687', 0),
            ('NE', 'Niger', 'Niger', 'NER', '227', 0),
            ('NF', 'Norfolk', 'Norfolk Island', 'NFK', '672', 0),
            ('NG', 'Nigeria', 'Nigeria', 'NGA', '234', 0),
            ('NI', 'Nicaragua', 'Nicaragua', 'NIC', '505', 0),
            ('NL', 'Nederland', 'Netherlands', 'NLD', '31', 1),
            ('NO', 'Noorwegen', 'Norway', 'NOR', '47', 0),
            ('NP', 'Nepal', 'Nepal', 'NPL', '977', 0),
            ('NR', 'Nauru', 'Nauru', 'NRU', '674', 0),
            ('NU', 'Niue', 'Niue', 'NIU', '683', 0),
            ('NZ', 'Nieuw-Zeeland', 'New Zealand', 'NZL', '64', 0),
            ('OM', 'Oman', 'Oman', 'OMN', '968', 0),
            ('PA', 'Panama', 'Panama', 'PAN', '507', 0),
            ('PE', 'Peru', 'Peru', 'PER', '51', 0),
            ('PF', 'Frans-Polynesië', 'French Polynesia', 'PYF', '689', 0),
            ('PG', 'Papoea-Nieuw-Guinea', 'Papua New Guinea', 'PNG', '675', 0),
            ('PH', 'Filipijnen', 'Philippines', 'PHL', '63', 0),
            ('PK', 'Pakistan', 'Pakistan', 'PAK', '92', 0),
            ('PL', 'Polen', 'Poland', 'POL', '48', 1),
            ('PM', 'Saint-Pierre en Miquelon', 'St. Pierre and Miquelon', 'SPM', '508', 0),
            ('PN', 'Pitcairneilanden', 'Pitcairn', 'PCN', '64', 0),
            ('PR', 'Puerto Rico', 'Puerto Rico', 'PRI', '1-787', 0),
            ('PS', 'Palestina', 'Palestine', 'PSE', '970', 0),
            ('PT', 'Portugal', 'Portugal', 'PRT', '351', 1),
            ('PW', 'Palau', 'Palau', 'PLW', '680', 0),
            ('PY', 'Paraguay', 'Paraguay', 'PRY', '595', 0),
            ('QA', 'Qatar', 'Qatar', 'QAT', '974', 0),
            ('RE', 'Réunion', 'Réunion', 'REU', '262', 0),
            ('RO', 'Roemenië', 'Romania', 'ROU', '40', 1),
            ('RS', 'Servië', 'Serbia', 'SRB', '381', 0),
            ('RU', 'Rusland', 'Russian Federation', 'RUS', '7', 0),
            ('RW', 'Rwanda', 'Rwanda', 'RWA', '250', 0),
            ('SA', 'Saoedi-Arabië', 'Saudi Arabia', 'SAU', '966', 0),
            ('SB', 'Salomonseilanden', 'Solomon Islands', 'SLB', '677', 0),
            ('SC', 'Seychellen', 'Seychelles', 'SYC', '248', 0),
            ('SD', 'Soedan', 'Sudan', 'SDN', '249', 0),
            ('SE', 'Zweden', 'Sweden', 'SWE', '46', 1),
            ('SG', 'Singapore', 'Singapore', 'SGP', '65', 0),
            ('SH', 'Sint-Helena, Ascension en Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', '290', 0),
            ('SI', 'Slovenië', 'Slovenia', 'SVN', '386', 1),
            ('SJ', 'Spitsbergen en Jan Mayen', 'Svalbard and Jan Mayen Islands', 'SJM', '47', 0),
            ('SK', 'Slowakije', 'Slovakia', 'SVK', '421', 1),
            ('SL', 'Sierra Leone', 'Sierra Leone', 'SLE', '232', 0),
            ('SM', 'San Marino', 'San Marino', 'SMR', '378', 0),
            ('SN', 'Senegal', 'Senegal', 'SEN', '221', 0),
            ('SO', 'Somalië', 'Somalia', 'SOM', '252', 0),
            ('SR', 'Suriname', 'Suriname', 'SUR', '597', 0),
            ('SS', 'Zuid-Soedan', 'South Sudan', 'SSD', '728', 0),
            ('ST', 'Sao Tomé en Principe', 'Sao Tome and Principe', 'STP', '239', 0),
            ('SV', 'El Salvador', 'El Salvador', 'SLV', '503', 0),
            ('SX', 'Sint Maarten (Nederlands deel)', 'Sint Maarten (Dutch part)', 'SXM', '1-721', 0),
            ('SY', 'Syrië', 'Syrian Arab Republic', 'SYR', '963', 0),
            ('SZ', 'Eswatini', 'Eswatini', 'SWZ', '268', 0),
            ('TC', 'Turks- en Caicoseilanden', 'Turks and Caicos Islands', 'TCA', '1-649', 0),
            ('TD', 'Tsjaad', 'Chad', 'TCD', '235', 0),
            ('TF', 'Franse Zuidelijke en Antarctische Gebieden', 'French Southern Territories', 'ATF', '262', 0),
            ('TG', 'Togo', 'Togo', 'TGO', '228', 0),
            ('TH', 'Thailand', 'Thailand', 'THA', '66', 0),
            ('TJ', 'Tadzjikistan', 'Tajikistan', 'TJK', '992', 0),
            ('TK', 'Tokelau', 'Tokelau', 'TKL', '690', 0),
            ('TL', 'Oost-Timor', 'Timor-Leste', 'TLS', '670', 0),
            ('TM', 'Turkmenistan', 'Turkmenistan', 'TKM', '993', 0),
            ('TN', 'Tunesië', 'Tunisia', 'TUN', '216', 0),
            ('TO', 'Tonga', 'Tonga', 'TON', '676', 0),
            ('TR', 'Turkije', 'Turkey', 'TUR', '90', 0),
            ('TT', 'Trinidad en Tobago', 'Trinidad and Tobago', 'TTO', '1-868', 0),
            ('TV', 'Tuvalu', 'Tuvalu', 'TUV', '688', 0),
            ('TW', 'Taiwan', 'Taiwan', 'TWN', '886', 0),
            ('TZ', 'Tanzania', 'Tanzania, United Republic of', 'TZA', '255', 0),
            ('UA', 'Oekraïne', 'Ukraine', 'UKR', '380', 0),
            ('UG', 'Oeganda', 'Uganda', 'UGA', '256', 0),
            ('UM', 'Kleine afgelegen eilanden van de Verenigde Staten', 'United States Minor Outlying Islands', 'UMI', '246', 0),
            ('US', 'Verenigde Staten', 'United States of America', 'USA', '1', 0),
            ('UY', 'Uruguay', 'Uruguay', 'URY', '598', 0),
            ('UZ', 'Oezbekistan', 'Uzbekistan', 'UZB', '998', 0),
            ('VA', 'Vaticaanstad', 'Vatican City State (Holy See)', 'VAT', '379', 0),
            ('VC', 'Saint Vincent en de Grenadines', 'Saint Vincent and the Grenadines', 'VCT', '1-784', 0),
            ('VE', 'Venezuela', 'Venezuela', 'VEN', '58', 0),
            ('VG', 'Britse Maagdeneilanden', 'Virgin Islands (British)', 'VGB', '1-284', 0),
            ('VI', 'Amerikaanse Maagdeneilanden', 'Virgin Islands (U.S.)', 'VIR', '1-340', 0),
            ('VN', 'Vietnam', 'Vietnam', 'VNM', '84', 0),
            ('VU', 'Vanuatu', 'Vanuatu', 'VUT', '678', 0),
            ('WF', 'Wallis en Futuna', 'Wallis and Futuna', 'WLF', '681', 0),
            ('WS', 'Samoa', 'Samoa', 'WSM', '685', 0),
            ('YE', 'Jemen', 'Yemen', 'YEM', '967', 0),
            ('YT', 'Mayotte', 'Mayotte', 'MYT', '262', 0),
            ('ZA', 'Zuid-Afrika', 'South Africa', 'ZAF', '27', 0),
            ('ZM', 'Zambia', 'Zambia', 'ZMB', '260', 0),
            ('ZW', 'Zimbabwe', 'Zimbabwe', 'ZWE', '263', 0);
        ");
    }
}
