<?php

namespace App\View\Components\TallStackUi\Colors;

use Illuminate\View\Component;

class ButtonColors
{
    /**
     * Background colors.
     */
    public function backgroundColors(Component $component): array
    {
        return [
            'solid' => [
                'success' => 'bg-success-500',
                'danger'  => 'bg-danger-500',
                'warning' => 'bg-warning-500',
                'info'    => 'bg-info-500',

                'white'     => null,
                'black'     => null,
                'primary'   => 'bg-primary-700 text-white',
                'secondary' => 'bg-secondary-700',
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
            'outline' => [
                'white'     => null,
                'black'     => null,
                'primary'   => null,
                'secondary' => null,
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
            'light' => [
                'white'     => null,
                'black'     => null,
                'primary'   => null,
                'secondary' => null,
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
            'flat' => [
                'white'     => null,
                'black'     => null,
                'primary'   => null,
                'secondary' => null,
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
        ];
    }

    /**
     * Icon colors.
     */
    public function iconColors(Component $component): array
    {
        return [
            'solid' => [
                'white'     => null,
                'black'     => null,
                'primary'   => null,
                'secondary' => null,
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
            'outline' => [
                'white'     => null,
                'black'     => null,
                'primary'   => null,
                'secondary' => null,
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
            'light' => [
                'white'     => null,
                'black'     => null,
                'primary'   => null,
                'secondary' => null,
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
            'flat' => [
                'white'     => null,
                'black'     => null,
                'primary'   => null,
                'secondary' => null,
                'slate'     => null,
                'gray'      => null,
                'zinc'      => null,
                'neutral'   => null,
                'stone'     => null,
                'red'       => null,
                'orange'    => null,
                'amber'     => null,
                'yellow'    => null,
                'lime'      => null,
                'green'     => null,
                'emerald'   => null,
                'teal'      => null,
                'cyan'      => null,
                'sky'       => null,
                'blue'      => null,
                'indigo'    => null,
                'violet'    => null,
                'purple'    => null,
                'fuchsia'   => null,
                'pink'      => null,
                'rose'      => null,
            ],
        ];
    }
}
